export * from './static/HomePage';
export * from './static/NotFoundPage';
export * from './LoginPage';
export * from './SignupPage';
export * from './DashboardPage';
export * from './SingleVehiclePage';
export * from './SingleWorkshopPage';
export * from './NewVehiclePage';
export * from './EditVehiclePage';